CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT, 
  Name NVARCHAR(255),
  Email NVARCHAR(255),
  Password NVARCHAR(255),
  ProfilePic BLOB,
  Biblio NVARCHAR(255)
);

CREATE TABLE subjects (
  id INTEGER PRIMARY KEY AUTO_INCREMENT, 
  Name NVARCHAR(255),
  Image BLOB
);

CREATE TABLE Questions_PT (
  id INTEGER PRIMARY KEY AUTO_INCREMENT, 
  IDSubject INTEGER, 
  Question NVARCHAR(255),
  Difficulty INTEGER, 
  RightAnswer NVARCHAR(255),
  Wrong1 NVARCHAR(255),
  Wrong2 NVARCHAR(255),
  Wrong3 NVARCHAR(255),
  CONSTRAINT fk_questSubj FOREIGN KEY (IDSubject) REFERENCES subjects (id)
);

CREATE TABLE Questions_ENG (
  id INTEGER PRIMARY KEY AUTO_INCREMENT, 
  IDSubject INTEGER, 
  Question NVARCHAR(255),
  Difficulty INTEGER, 
  RightAnswer NVARCHAR(255),
  Wrong1 NVARCHAR(255),
  Wrong2 NVARCHAR(255),
  Wrong3 NVARCHAR(255),
  CONSTRAINT fk_questSubjEng FOREIGN KEY (IDSubject) REFERENCES subjects (id)
);

CREATE TABLE UserResults (
  id INTEGER PRIMARY KEY AUTO_INCREMENT, 
  IDSubject INTEGER, 
  IDUser INTEGER, 
  Score INTEGER, 
  NumCorrectAns INTEGER, 
  NumWrongAns INTEGER, 
  TimeToSolve TIME NULL, 
  CONSTRAINT fk_resultSubj FOREIGN KEY (IDSubject) REFERENCES subjects (id), CONSTRAINT fk_resultUser FOREIGN KEY (IDUser) REFERENCES users (id)
);


CREATE TABLE UserFriends (
  id INTEGER PRIMARY KEY AUTO_INCREMENT, 
  IDUser INTEGER, 
  IDFriend INTEGER, 
  CONSTRAINT fk_frindUser FOREIGN KEY (IDUser) REFERENCES users (id), 
  CONSTRAINT fk_userfriend FOREIGN KEY (IDFriend) REFERENCES users (id)
);